### ISSUE TITLE
Duplicated cookie

### ISSUE THREAD

**Issue by tree1891** [franmontiel/PersistentCookieJar#23]
I have requested to login using basic authentication, it redirects to user details.
After it finished, I have checked cookie.

wfwaf-authcookie-c448b9945c37d9cc4b94b09f3d21632a=27419%7Cadministrator%7Cbfbc704c50089e8b848ca10c14b1b74ad4a309992102e3faf98bdd782d6aeb47; expires=Wed, 09 Nov 2016 14:19:08 GMT; path=/; httponly
wfvt_4021301540=5822879cee322; expires=Wed, 09 Nov 2016 02:49:08 GMT; path=/; httponly
wfvt_4021301540=5822879e5f5cc; expires=Wed, 09 Nov 2016 02:49:10 GMT; path=/; httponly

I found wfvt_4021301540 duplicated.

I think one is for example.com, other for www.example.com.
I have requested to example.com.

**Comment by franmontiel** [comment]
I think that the behavior that you are describing is the correct one, let me explain:
In this case if your server is setting cookies for different domains they should be both stored if they aren't expired.
If you are receiving this cookie duplicated should be because both cookies match the url. For your information I am relying in the matches() method of the okhttp3.Cookie to check if a cookie match with a determinate url.
