### ISSUE TITLE
[Question] ClearableCookieJar initialization

### ISSUE THREAD

**Issue by tree1891** [franmontiel/PersistentCookieJar#28]
I have a static instance of ClearableCookieJar and init it once at the beginning.
Is it right way?

**Comment by franmontiel** [comment]
Yes, I don't see any problem with your usage of the library.

**Comment by tree1891** [comment]
But sometimes it is null in Activity or Fragment, so it is used to init again.

**Comment by franmontiel** [comment]
This seems more like a development problem that is not related with the library. You're missing the reference to the object maybe due to Android lifecycle...
There should be no problem if you initialize the CookieJar in your Application class making it an instance attribute (non-static). You can also use a dependency injector like Dagger.
